language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: oTfblnOmDTNE7DvUrOv8p2OfDpKv6I6OQi2EFSUnnnwlrRbyDWYXa+chOPdhmNhM9nMDY+tV5wTYuWOrg13xIgChWJoiwWruwzM3LN9OlZWl8yy+f8Y2NZu19GyldSbAY2OGMnDhLFTWL4zOQ9Ek0OnSkunuSqIu8zkonEb7dbffrUSJ3WMje9rCkfRWZp6ZtutNCa7CvSvxR/RiGwkYYehurOe1YZaU101RGmb7ZBFiQavb49SoLW5z3Y5J9c+IEJZKncGIczgiYdj/WoOUAtjXX+n7NhQPDZPWyBX65NXWxwzxPRP775o7u/APyubJqfLInPnpg8RWsJvGXvpCiakYeseAPWCgmkbhQp4t1w9G3hBHH/ZnN+guimcUp1ctLNgb2A074NJCCevJfP6i0tg8XTjg2Wk0byY8uMXXMkZx7X3vCUof+fTGqIG7Kt9vNnwQCGPY5zj8Q5xrYpVuZsxGoQXzNxhn3I3eXd9R8sBfmTkepneUClSn9uxNCIzgrGmUkBIDZZE1dl7hcIl0rvqZA9Y1R5HBypavGI/gEak8C1AIRwv0iF5Q7HB/XXou6ECk+pNlMDb1ycEqhNefoFhOw51G8gtdTOR3kG6upjnPCKExqHfDhZW+IZ22eZZciOtBWqST2Z9b9ZGwxtNXIUbWSPNDOZrFowzb5AQe6P0=
  on:
    branch: master
    tags: true
    repo: deg-skeletor/skeletor-cli
